[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
  force = true
  methods = ["POST"]
  headers = { Stripe-Signature = ":stripe-signature" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]